### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by cloudpilot** [EugeneDae/Force-Paste#1]
Hi,
I don't know why, but it won't paste numbers. No problem with letters and symbols but numbers just won't paste.
Any idea what could be the cause of this ?

Thx a lot

**Comment by EugeneDae** [comment]
Interesting.

Have you ever been able to paste numbers with this app?
What OS X version are you on?
Do you use any non-*US-English international* input sources? ([This is what I mean](https://cloud.githubusercontent.com/assets/980835/6051771/12779742-acdc-11e4-93db-ec1792fd1432.png)).

**Comment by cloudpilot** [comment]
No never been able to past numbers with this app but I used it for the first time yesterday and the numbers issue appeared on the very first use. I am on 10.10.2 (Hackintosh). Indeed, being french and dual booting I'm using French - Numerical and French- PC as input sources.

**Comment by cloudpilot** [comment]
Alright so with the French input sources, I tried to past "1234567890" and it pasted "&é”’(§è!çà".
Just tried with the U.S keyboard input and numbers do past correctly with this input.

If you have any idea on how to resolve this issue with a non US input source that would be awesome.

Thx

**Comment by cloudpilot** [comment]
(Using an Apple wireless keyboard without a numerical keyboard)

**Comment by EugeneDae** [comment]
Please try the new [beta version](https://github.com/EugeneDae/Force-Paste/releases/download/1.0.1b/Force-Paste.zip), it should fix the issue.

**Comment by cloudpilot** [comment]
Working perfectly !
Thank you very much for looking it up and fixing it so fast.

Much appreciated
Peace

**Comment by EugeneDae** [comment]
Thanks for taking time to report the problem!
