### ISSUE TITLE
Mojave support

### ISSUE THREAD

**Issue by scfurl** [EugeneDae/Force-Paste#7]
Since upgrading to Mojave, I now get an error "Force Paste is not allowed to send keystrokes.  System Events got an error: Force Paste is not allowed to send keystrokes. (1002)"

Tried a rebuild, no change

**Comment by EugeneDae** [comment]
Thanks for letting know. Can you please try dragging Force Paste.app into System Preferences > Security & Privacy > Accessibility and see if it helps?

![accessibility](https://user-images.githubusercontent.com/980835/46075001-77d61800-c189-11e8-9bd8-3350d3148723.png)

**Comment by tohn** [comment]
Thanks a lot, got the same error, your solution worked for me!

**Comment by EugeneDae** [comment]
@tohn super! thanks for reporting back

**Comment by scfurl** [comment]
Me too.  Thanks!!

**Comment by jutudawam** [comment]
Hey. Mojave seems to be stopping ForcePaste from working even when doing the above fix. Has anyone got another fix? Thanks.

**Comment by EugeneDae** [comment]
@jutudawam Could you please post a screenshot of your Security & Privacy window with Force Paste?

**Comment by dsjoerg** [comment]
Thank goodness, I can't live without Force Paste !!!

**Comment by hobbes444** [comment]
This issue is back for me since Big Sur 11.4. Removing the app from Privacy>Accessibility and re-adding it, does not solve the issue.

**Comment by rdouma** [comment]
> This issue is back for me since Big Sur 11.4. Removing the app from Privacy>Accessibility and re-adding it, does not solve the issue.

For me too... Any workarounds? I deleted/reinstalled the app, removed it from Accessibility, added it again. It's also listed under Automation, where it cannot be removed, only unchecked.

![2021-07-12_15-08-35](https://user-images.githubusercontent.com/1451271/125335590-1a53eb80-e323-11eb-9cc9-19c28f35c706.jpg)

**Comment by tohn** [comment]
@rdouma try this: https://github.com/EugeneDae/Force-Paste/issues/12#issuecomment-853273492

**Comment by rdouma** [comment]
Yes, that did the trick! Thanks!
